blank_issues_enabled: false
contact_links:
  - name: 'ğŸ”Œ Task for Visual Studio Code'
    url: https://github.com/go-task/vscode-task
    about: 'Issues related to the Visual Studio Code extension should be opened here.'
  - name: 'ğŸ’¬ Help forum on Discord'
    url: https://discord.com/channels/974121106208354339/1025054680289660989
    about: 'The #help channel on our Discord is the best way to get help from the community.'
  - name: 'â“ Questions, Ideas and General Discussions'
    url: https://github.com/go-task/task/discussions
    about: 'Ask questions and discuss general ideas with the community.'
