name: Lint

on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        go-version: [1.23.x, 1.24.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-version}}

      - uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.0

  lint-jsonschema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - uses: actions/checkout@v4

      - name: install check-jsonschema
        run: python -m pip install 'check-jsonschema==0.27.3'

      - name: check-jsonschema (metaschema)
        run: check-jsonschema --check-metaschema website/static/schema.json
  check_doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v46
        with:
          files: website/versioned_docs/**

      - uses: actions/github-script@v7
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        with:
          script: |
            core.setFailed('website/versioned_docs has changed. Instead you need to update the docs in the website/docs folder.')
  check_schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v46
        with:
          files: |
            website/static/schema.json
            website/static/schema-taskrc.json
      - uses: actions/github-script@v7
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        with:
          script: |
            core.setFailed('schema.json or schema-taskrc.json has changed. Instead you need to update next-schema.json or next-schema-taskrc.json.')
